# Generated by Django 4.0.2 on 2022-02-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_rename_fname_employ_address_remove_employ_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
