# Generated by Django 4.0.2 on 2022-03-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_manager_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date_joined',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
