# Generated by Django 4.0.2 on 2022-03-01 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chef', models.CharField(max_length=50)),
                ('waiter', models.CharField(max_length=50)),
                ('item', models.CharField(max_length=500, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('price', models.CharField(max_length=20, null=True)),
                ('delivery', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_ready', models.BooleanField(default=False)),
                ('is_picked', models.BooleanField(default=False)),
                ('is_payed', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
