# Generated by Django 4.0.2 on 2022-03-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='img',
            field=models.ImageField(upload_to='pics/'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='img',
            field=models.ImageField(upload_to='pics/'),
        ),
    ]
