# Generated by Django 4.0.2 on 2022-03-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0003_alter_meal_img_alter_menu_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='menu',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
