# Generated by Django 4.0.2 on 2022-03-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0005_order_date_alter_meal_img_alter_menu_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='datet',
            field=models.CharField(default='2022-03-10', max_length=10),
            preserve_default=False,
        ),
    ]
