# Generated by Django 4.0.2 on 2022-03-25 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0006_purchase_datet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
