# Generated by Django 4.0.2 on 2022-03-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0007_delete_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt',
            field=models.ImageField(default=0, upload_to='receipts'),
            preserve_default=False,
        ),
    ]
